### ISSUE TITLE
Contact form not working

### ISSUE THREAD

**Issue by AaronAguilar** [EditLLC/client-knot-away#15]
I tested it out using my email address and it wasn't working correctly. Could you have a look at it for me? This is the last push b15ca989e978c45959de1906edc2c7def9a352b0

**Comment by rodneystrong** [comment]
Absolutely sir. Thanks for creating this.

**Comment by rodneystrong** [comment]
Turns out the default main.js had a section for handling the submission of the form before our  method="POST" on the form could redirect the user to the contact-form-handler.php page. 

I fixed the code but the contact form now produces a 405, which is actually correct since gh-pages doesn't allow us to run php, at least i think that's the issue. 

I'll keep this issue open until we push the site live so I can test again when it's not on gh-pages.

**Comment by AaronAguilar** [comment]
Okay, thanks! Would you mind explaining further in person so that I know what to look for if this happens again in the future?

**Comment by rodneystrong** [comment]
Gladly. Remind me next time we both have a free minute.

**Comment by rodneystrong** [comment]
Successfully tested and the form is now working after site has gone live. Congrats @AaronAguilar ! Another of your client sites has gone live

Let's discuss on Monday what this issue is at 3p
